package com.sw.model;

public class Address {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.addressid
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    private Integer addressid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.userid
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.receivename
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    private String receivename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.receivephone
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    private String receivephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.addressid
     *
     * @return the value of address.addressid
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public Integer getAddressid() {
        return addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.addressid
     *
     * @param addressid the value for address.addressid
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public void setAddressid(Integer addressid) {
        this.addressid = addressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.userid
     *
     * @return the value of address.userid
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.userid
     *
     * @param userid the value for address.userid
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.receivename
     *
     * @return the value of address.receivename
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public String getReceivename() {
        return receivename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.receivename
     *
     * @param receivename the value for address.receivename
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public void setReceivename(String receivename) {
        this.receivename = receivename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.receivephone
     *
     * @return the value of address.receivephone
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public String getReceivephone() {
        return receivephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.receivephone
     *
     * @param receivephone the value for address.receivephone
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public void setReceivephone(String receivephone) {
        this.receivephone = receivephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address
     *
     * @return the value of address.address
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address
     *
     * @param address the value for address.address
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }
}