package com.sw.model;

import java.math.BigDecimal;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goodsid
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goodsclass
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    private String goodsclass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goodsname
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    private String goodsname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.purchaseprice
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    private BigDecimal purchaseprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.unit
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.brand
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    private String brand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.remark
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goodsid
     *
     * @return the value of goods.goodsid
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goodsid
     *
     * @param goodsid the value for goods.goodsid
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goodsclass
     *
     * @return the value of goods.goodsclass
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public String getGoodsclass() {
        return goodsclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goodsclass
     *
     * @param goodsclass the value for goods.goodsclass
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public void setGoodsclass(String goodsclass) {
        this.goodsclass = goodsclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goodsname
     *
     * @return the value of goods.goodsname
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goodsname
     *
     * @param goodsname the value for goods.goodsname
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.purchaseprice
     *
     * @return the value of goods.purchaseprice
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public BigDecimal getPurchaseprice() {
        return purchaseprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.purchaseprice
     *
     * @param purchaseprice the value for goods.purchaseprice
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public void setPurchaseprice(BigDecimal purchaseprice) {
        this.purchaseprice = purchaseprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.price
     *
     * @return the value of goods.price
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.price
     *
     * @param price the value for goods.price
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.unit
     *
     * @return the value of goods.unit
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.unit
     *
     * @param unit the value for goods.unit
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.brand
     *
     * @return the value of goods.brand
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.brand
     *
     * @param brand the value for goods.brand
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.remark
     *
     * @return the value of goods.remark
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.remark
     *
     * @param remark the value for goods.remark
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}