package com.sw.model;

public class Orderdetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetails.orderdetailsid
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    private Integer orderdetailsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetails.ordervode
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    private String ordervode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetails.goodsid
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderdetails.number
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    private Integer number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetails.orderdetailsid
     *
     * @return the value of orderdetails.orderdetailsid
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public Integer getOrderdetailsid() {
        return orderdetailsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetails.orderdetailsid
     *
     * @param orderdetailsid the value for orderdetails.orderdetailsid
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public void setOrderdetailsid(Integer orderdetailsid) {
        this.orderdetailsid = orderdetailsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetails.ordervode
     *
     * @return the value of orderdetails.ordervode
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public String getOrdervode() {
        return ordervode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetails.ordervode
     *
     * @param ordervode the value for orderdetails.ordervode
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public void setOrdervode(String ordervode) {
        this.ordervode = ordervode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetails.goodsid
     *
     * @return the value of orderdetails.goodsid
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetails.goodsid
     *
     * @param goodsid the value for orderdetails.goodsid
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderdetails.number
     *
     * @return the value of orderdetails.number
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderdetails.number
     *
     * @param number the value for orderdetails.number
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
}