package com.sw.model;

public class Sale {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.saleid
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    private Integer saleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.salename
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    private String salename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.nickname
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale.salepassword
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    private String salepassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.saleid
     *
     * @return the value of sale.saleid
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public Integer getSaleid() {
        return saleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.saleid
     *
     * @param saleid the value for sale.saleid
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public void setSaleid(Integer saleid) {
        this.saleid = saleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.salename
     *
     * @return the value of sale.salename
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public String getSalename() {
        return salename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.salename
     *
     * @param salename the value for sale.salename
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public void setSalename(String salename) {
        this.salename = salename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.nickname
     *
     * @return the value of sale.nickname
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.nickname
     *
     * @param nickname the value for sale.nickname
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale.salepassword
     *
     * @return the value of sale.salepassword
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public String getSalepassword() {
        return salepassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale.salepassword
     *
     * @param salepassword the value for sale.salepassword
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    public void setSalepassword(String salepassword) {
        this.salepassword = salepassword;
    }

	@Override
	public String toString()
	{
		return "Sale [saleid=" + saleid + ", salename=" + salename + ", nickname=" + nickname + ", salepassword="
				+ salepassword + "]";
	}
    
}