package com.sw.dao;

import com.sw.model.Goodsorders;
import com.sw.model.GoodsordersExample;
import com.sw.util.Page;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsordersMapper {
    
	List<Goodsorders> goodsOrderALLByPage(@Param("page")Page page);
	List<Goodsorders> goodsOrderALLByDate(@Param("startDate")String startDate,@Param("endDate")String endDate);
    String getToDayMaxOrderCode(@Param("date") String date);
    Integer goodsordersMaxId();
    
    
    //以上是自己的定义的方法
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsorders
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    long countByExample(GoodsordersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsorders
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    int deleteByExample(GoodsordersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsorders
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    int deleteByPrimaryKey(Integer orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsorders
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    int insert(Goodsorders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsorders
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    int insertSelective(Goodsorders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsorders
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    List<Goodsorders> selectByExample(GoodsordersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsorders
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    Goodsorders selectByPrimaryKey(Integer orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsorders
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    int updateByExampleSelective(@Param("record") Goodsorders record, @Param("example") GoodsordersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsorders
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    int updateByExample(@Param("record") Goodsorders record, @Param("example") GoodsordersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsorders
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    int updateByPrimaryKeySelective(Goodsorders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsorders
     *
     * @mbg.generated Sun Sep 02 15:46:59 CST 2018
     */
    int updateByPrimaryKey(Goodsorders record);
    
    

    
}